export const pokemonColorTypes = new Map([
  ['normal', 'black'],
  ['fighting', 'purple'],
  ['flying', 'blue'],
  ['poison', 'violet'],
  ['ground', 'brown'],
  ['rock', 'darkgrey'],
  ['bug', 'fuchsia'],
  ['ghost', 'coral'],
  ['steel', 'grey'],
  ['fire', 'red'],
  ['water', 'aquamarine'],
  ['grass', 'lime'],
  ['electric', 'orange'],
  ['psychic', 'blueviolet'],
  ['ice', 'blanchedalmond'],
  ['dragon', 'chocolate'],
  ['dark', 'darkolivegreen'],
  ['fairy', 'darkorange'],
  ['unknown', 'black'],
  ['shadow', 'darksalmon'],
]);
